---
kind: pipeline
name: main

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: grafana/grafana-build
    tags:
    - latest
    - main
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password

trigger:
  event:
  - push
  branch:
  - main
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: dockerhub_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: dockerhub_password
---
kind: signature
hmac: 8b823e93dfec61db66175d78aabe559491352b9deacd7c25a522e4f3d47376b9

...
