name: PR Integration tests

on:
  pull_request: {}
  issue_comment:
    types: [created]

jobs:
  grafana-integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [main, v11.2.x, v11.1.x, v11.0.x, v10.4.x, v10.3.x]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Checkout grafana
        uses: actions/checkout@v4
        with:
          repository: grafana/grafana
          ref: ${{ matrix.version }}
          path: grafana
      - name: Clean runner
        run: |
          df -h
          docker builder prune -f
          docker system prune -a -f
          sudo rm -rf /opt/google/chrome
          sudo rm -rf /opt/microsoft/msedge
          sudo rm -rf /opt/microsoft/powershell
          sudo rm -rf /opt/pipx
          sudo rm -rf /usr/lib/mono
          sudo rm -rf /usr/local/julia*
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          df -h
      - uses: dagger/dagger-for-github@v6
        with:
          verb: run
          args: go run ./cmd artifacts -a targz:grafana:linux/amd64 --grafana-dir=grafana